version: '3'
services:
  app:
    container_name: node
    restart: always
    build: .
    links:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
